# .github/workflows/build-and-push-docker.yml
name: Build and Push Docker Image to GCP Artifact Registry

on:
  workflow_call:  # Allow this workflow to be reusable
    inputs:
      docker_image_name:
        required: true
        type: string
      docker_tag:
        required: true
        type: string
      #gcp_project_id:
        #required: true
        #type: string
      #gcp_region:
        #required: true
        #type: string
        
    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_REGION:
        required: true
      GCP_CREDENTIALS:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}  # Access secret passed from calling workflow
      
      - name: Secrets Echo
        run: |
          echo "GCP_PROJECT_ID = ${{ secrets.GCP_PROJECT_ID }}"
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.docker_image_name }}:${{ inputs.docker_tag }} .

      - name: Push Docker Image to Artifact Registry
        run: |
          # Set the correct GCP Artifact Registry repository
          gcloud auth configure-docker ${{ secrets.GCP_REGION}}-docker.pkg.dev --quiet
          docker tag ${{ inputs.docker_image_name }}:${{ inputs.docker_tag }} ${{ secrets.GCP_REGION}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/${{ inputs.docker_image_name }}:${{ inputs.docker_tag }}
          docker push ${{ secrets.GCP_REGION}}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/${{ inputs.docker_image_name }}:${{ inputs.docker_tag }}
