# .github/workflows/build-and-push-docker.yml
name: Build and Push Docker Image to GCP Artifact Registry

on:
  workflow_call:  # Allow this workflow to be reusable
    inputs:
      docker_image_name:
        required: true
        type: string
      docker_tag:
        required: true
        type: string
      gcp_project_id:
        required: true
        type: string
      gcp_region:
        required: true
        type: string
      gcp_service_account_key:  # Optional, can pass via secrets if needed
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.gcp_project_id }}
          credentials_json: ${{ inputs.gcp_service_account_key }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.docker_image_name }}:${{ inputs.docker_tag }} .

      - name: Push Docker Image to Artifact Registry
        run: |
          # Set the correct GCP Artifact Registry repository
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet
          docker tag ${{ inputs.docker_image_name }}:${{ inputs.docker_tag }} asia-south1-docker.pkg.dev/${{ inputs.gcp_project_id }}/my-repo/${{ inputs.docker_image_name }}:${{ inputs.docker_tag }}
          docker push asia-south1-docker.pkg.dev/${{ inputs.gcp_project_id }}/my-repo/${{ inputs.docker_image_name }}:${{ inputs.docker_tag }}
